version: "3.7"
services:
  app:
    build: 
      context: .
    volumes:
      - .:/antimatter
    ports:
      - 3000:3000
    image: app:react  
    container_name: antimatter
    command: npm start