version: "3.8"
networks:
  main:

services:
  jitsu:
    container_name: jitsu
    image: jitsucom/jitsu
    environment:
      - REDIS_URL=redis://redis:6379
      - TERM=xterm-256color
    depends_on:
      - redis
    volumes:
      - ./compose-data/configurator/data/logs:/home/configurator/data/logs
      - ./compose-data/server/data/logs:/home/eventnative/data/logs
      - ./compose-data/server/data/logs/events:/home/eventnative/data/logs/events
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/home/eventnative/data/airbyte
    restart: always
    ports:
      - "8000:8000"
    networks:
      - main
  redis:
    container_name: jitsu_redis
    image: redis:6.2.4-alpine
    volumes:
      - ./compose-data/redis/data:/data
    restart: always
    networks:
      - main

volumes:
  workspace:
    name: jitsu_workspace
